// Command genpalette writes core/push3.Palette out as palette.json, once
// per process-loaded example module directory under examples/modules/, so a
// module written in a language that cannot import the Go push3 package (JS,
// Python, anything else) can still look up a Push palette color by name or
// by raw 0-127 index instead of hand-copying RGB literals.
//
// push3.Palette itself changes rarely (it's a fixed, SysEx-sourced hardware
// table — see core/push3/colors.go), so this is a manual regeneration step,
// not a build-time dependency: run it after any change to that table.
//
//	go run ./cmd/genpalette
//
// Deliberately outside internal/host: like cmd/screensim, this only needs
// core/push3, not internal/display's gousb/cgo dependency, so it runs
// anywhere `go run` does.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/federico-pepe/ableton-push-hack/core/push3"
)

// paletteEntry is one row of the generated palette.json — a raw 0-127
// hardware index resolved to its name and RGBA, mirroring
// push3.PaletteEntry's fields but with a JSON-friendly, lowercase shape
// (r/g/b/a rather than an embedded color.NRGBA) so a module in any language
// can decode it with no Go-specific knowledge.
type paletteEntry struct {
	Index int    `json:"index"`
	Name  string `json:"name"`
	R     uint8  `json:"r"`
	G     uint8  `json:"g"`
	B     uint8  `json:"b"`
	A     uint8  `json:"a"`
}

// paletteFile is the full generated document: byIndex covers every raw
// 0-127 hardware value (so palette["byIndex"][id] always resolves, the same
// "nearest defined entry at or below" guarantee push3.ColorForIndex makes,
// pre-computed here so a consumer never has to reimplement that search);
// byName covers only the ~90 actually-named entries, keyed by
// push3.NamedColors' own names, for the common "I want 'sky'" case.
type paletteFile struct {
	Source  string                  `json:"source"`
	ByIndex [128]paletteEntry       `json:"byIndex"`
	ByName  map[string]paletteEntry `json:"byName"`
}

func build() paletteFile {
	pf := paletteFile{
		Source: "core/push3/colors.go (generated by cmd/genpalette, do not hand-edit)",
		ByName: make(map[string]paletteEntry),
	}
	for i := range 128 {
		e := push3.ColorForIndex(byte(i))
		pf.ByIndex[i] = paletteEntry{Index: i, Name: e.Name, R: e.RGB.R, G: e.RGB.G, B: e.RGB.B, A: e.RGB.A}
	}
	for name, idx := range push3.NamedColors {
		e := push3.ColorForIndex(idx)
		pf.ByName[name] = paletteEntry{Index: int(idx), Name: e.Name, R: e.RGB.R, G: e.RGB.G, B: e.RGB.B, A: e.RGB.A}
	}
	return pf
}

func main() {
	root := "examples/modules"
	entries, err := os.ReadDir(root)
	if err != nil {
		log.Fatalf("genpalette: reading %s: %v", root, err)
	}

	pf := build()
	data, err := json.MarshalIndent(pf, "", "  ")
	if err != nil {
		log.Fatalf("genpalette: marshaling: %v", err)
	}
	data = append(data, '\n')

	written := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(root, e.Name())
		if _, err := os.Stat(filepath.Join(dir, "manifest.json")); err != nil {
			continue // not a module directory
		}
		out := filepath.Join(dir, "palette.json")
		if err := os.WriteFile(out, data, 0o644); err != nil {
			log.Fatalf("genpalette: writing %s: %v", out, err)
		}
		fmt.Println("wrote", out)
		written++
	}
	if written == 0 {
		log.Fatalf("genpalette: no module directories with manifest.json found under %s", root)
	}
}
