#!/usr/bin/env node
// knobs-js — two knobs of each composition the design system has (knob,
// knobfull, knobarc), each driven by its own encoder, each 0-100. Built as
// a quick test bench for knob rendering
// (docs/architecture/design-system.md's Knob/KnobFull/KnobArc rows —
// anti-aliased arc, knobStroke=2 by default as of 2026-08-22). Not a port
// of anything; exists purely to turn every encoder and eyeball the
// result.
//
// Each of the 8 columns lines up with its own physical encoder above the
// pad grid (960/8 = 120px per column, same convention the pad grid itself
// uses) — 6 knobs in columns 0-5, columns 6-7 left empty rather than
// spreading all 6 evenly across the full width. Encoders 7-8 (0-indexed
// 6-7) are unused, reserved for a future fourth pair.
//
// Same protocol as hello-js (see that module's comment for the full
// envelope shape). Each knob is given its own Color (widgets.Knob's fill/
// pointer color field) instead of leaving it unset — an unset Color falls
// back to the host Theme's Select color (the look every knob had before
// this field existed), so this module deliberately sets one on every knob
// to prove the override, rather than relying on the fallback.
//
// Endless-encoder convention: clamp the accumulator itself to [0,100] on
// every delta, same as modules/uidemo and modules/ui-text-demo — turning
// past a knob's limit stops there and reverses immediately, it doesn't
// wrap back to 0. See CHANGELOG.md's 2026-08-22 entry.

const fs = require("node:fs");
const path = require("node:path");
const readline = require("node:readline");

// palette.json is generated by cmd/genpalette from core/push3.Palette — see
// hello-js's copy of this comment for the full rationale.
const PALETTE = JSON.parse(fs.readFileSync(path.join(__dirname, "palette.json"), "utf8"));

function paletteColor(name) {
  const e = PALETTE.byName[name];
  if (!e) throw new Error(`unknown palette color ${JSON.stringify(name)}`);
  return { R: e.r, G: e.g, B: e.b, A: e.a };
}

function paletteById(id) {
  const e = PALETTE.byIndex[id];
  return { R: e.r, G: e.g, B: e.b, A: e.a };
}

const NUM_ENCODERS = 8;
const VALUE_SCALE = 2;

// One entry per drawn knob — op kind, label prefix, and fill Color, two
// encoders per composition (knob 1/2 -> KNOB 1/2, encoder 3/4 -> FULL 1/2,
// encoder 5/6 -> ARC 1/2). Encoders 6 and 7 (0-indexed) have no entry, so
// they're tracked in state.value like any other but never drawn.
const KNOBS = [
  { kind: "knob", label: "KNOB 1", color: paletteColor("sky") },
  { kind: "knob", label: "KNOB 2", color: paletteColor("lime") },
  { kind: "knobfull", label: "FULL 1", color: paletteColor("violet") },
  { kind: "knobfull", label: "FULL 2", color: paletteColor("pink_hot") },
  { kind: "knobarc", label: "ARC 1", color: paletteColor("orange") },
  { kind: "knobarc", label: "ARC 2", color: paletteColor("amber") },
];

function send(obj) {
  process.stdout.write(JSON.stringify(obj) + "\n");
}

function respond(id, result) {
  if (id === undefined || id === null) return;
  send({ id, result });
}

function respondError(id, message) {
  send({ id, error: message });
}

const state = {
  // value[i] is encoder i's accumulated value, clamped to [0,100] at write
  // time so a reversal past the limit responds immediately.
  value: new Array(NUM_ENCODERS).fill(0),
};

function clamp(v, lo, hi) {
  return Math.max(lo, Math.min(hi, v));
}

function handleEncoder(data) {
  const { index, delta } = data;
  if (index >= 0 && index < NUM_ENCODERS) {
    state.value[index] = clamp(state.value[index] + delta, 0, 100);
  }
}

// Op shapes mirror internal/module's Go types exactly — KnobParams is
// {cx,cy,r,k:{...}} (internal/module/frame.go) for all three knob kinds
// ("knob", "knobfull", "knobarc" — same param shape, different renderer),
// and widgets.Knob (the "k" object's type, in ableton-push-hack) has no
// json tags of its own, so its wire keys are its literal Go field names —
// Value/Min/Max/Color/ValueScale, capitalized — same reasoning as
// color.NRGBA's R/G/B/A in the other example modules. Label is left unset
// here on purpose — see the label-row comment below.
//
// VALUE_SCALE draws the value readout bigger (text.DrawScaled — same font,
// integer nearest-neighbor upscaled) instead of leaving ValueScale unset
// (1x, every knob's look before this field existed). Applied to every
// knob here to make it easy to eyeball on real hardware; a module would
// normally only set this on the controls where a bigger number actually
// earns its space.
const COLS = 8; // 960/8 = 120px per column, the same width the pad grid's own 8 columns use
const COL_W = 960 / COLS;
const LABEL_BASELINE = 153; // matches DrawStatusBar's own y+h-5 for the y=140,h=18 band this replaces
const CHAR_W = 7; // text.Width's per-char pixel width at 1x (core/gfx/text.Width), for centering labels ourselves

function draw() {
  const black = paletteById(0); // "off" — demonstrates the by-index lookup, paletteColor("off") works identically

  const ops = [
    { kind: "rect", params: { x: 0, y: 0, w: 960, h: 160, c: black } },
    { kind: "header", params: { y: 0, w: 960, h: 20, s: "pushapp - knobs-js (out of process)" } },
  ];

  const r = 30;
  const cy = 80; // vertical center of the content band between the header (0-20) and the label row (140-158)

  KNOBS.forEach(({ kind, label, color }, i) => {
    // Column i's center, not an even spread across all 6 — each knob lines
    // up under its own physical encoder, with columns 6-7 left empty.
    const cx = Math.round(i * COL_W + COL_W / 2);
    ops.push({
      kind,
      params: {
        cx,
        cy,
        r,
        k: { Value: state.value[i], Min: 0, Max: 100, Color: color, ValueScale: VALUE_SCALE },
      },
    });
    // Drawn ourselves in the row the old "turn encoders..." status hint
    // used to occupy, instead of via k.Label: the widget's own label sits
    // directly below the knob, which at ValueScale > 1 collides with
    // DrawKnobFull's now-taller value line — and k.Label always draws
    // t.Gray, which can't match each knob's own Color the way this does.
    // A generic hint isn't needed here either: each knob's own label,
    // right under it, already says what it is.
    const labelX = cx - Math.round((label.length * CHAR_W) / 2);
    ops.push({ kind: "text", params: { x: labelX, baseline: LABEL_BASELINE, s: label, c: color } });
  });

  return { ops, failed: 0 };
}

const rl = readline.createInterface({ input: process.stdin, terminal: false });

rl.on("line", (line) => {
  line = line.trim();
  if (!line) return;

  let env;
  try {
    env = JSON.parse(line);
  } catch {
    return;
  }

  const { method, id } = env;
  const params = env.params || {};

  switch (method) {
    case "init":
      respond(id, {});
      break;
    case "handle":
      if (params.kind === "encoder") {
        handleEncoder(params.data || {});
      }
      break;
    case "draw":
      respond(id, draw());
      break;
    case "close":
      respond(id, {});
      rl.close();
      process.exit(0);
      break;
    default:
      if (id !== undefined && id !== null) {
        respondError(id, `unknown method ${JSON.stringify(method)}`);
      }
  }
});
