#!/usr/bin/env node
// knobs-js — two knobs of each composition the design system has (knob,
// knobfull, knobarc), each driven by its own encoder, each 0-100. Built as
// a quick test bench for knob rendering
// (docs/architecture/design-system.md's Knob/KnobFull/KnobArc rows —
// anti-aliased arc, knobStroke=2 by default as of 2026-08-22). Not a port
// of anything; exists purely to turn every encoder and eyeball the
// result. Encoders 7-8 are unused, reserved for a future fourth pair.
//
// Same protocol as hello-js (see that module's comment for the full
// envelope shape). Each knob is given its own Color (widgets.Knob's fill/
// pointer color field) instead of leaving it unset — an unset Color falls
// back to the host Theme's Select color (the look every knob had before
// this field existed), so this module deliberately sets one on every knob
// to prove the override, rather than relying on the fallback.
//
// Endless-encoder convention: clamp the accumulator itself to [0,100] on
// every delta, same as modules/uidemo and modules/ui-text-demo — turning
// past a knob's limit stops there and reverses immediately, it doesn't
// wrap back to 0. See CHANGELOG.md's 2026-08-22 entry.

const fs = require("node:fs");
const path = require("node:path");
const readline = require("node:readline");

// palette.json is generated by cmd/genpalette from core/push3.Palette — see
// hello-js's copy of this comment for the full rationale.
const PALETTE = JSON.parse(fs.readFileSync(path.join(__dirname, "palette.json"), "utf8"));

function paletteColor(name) {
  const e = PALETTE.byName[name];
  if (!e) throw new Error(`unknown palette color ${JSON.stringify(name)}`);
  return { R: e.r, G: e.g, B: e.b, A: e.a };
}

function paletteById(id) {
  const e = PALETTE.byIndex[id];
  return { R: e.r, G: e.g, B: e.b, A: e.a };
}

const NUM_ENCODERS = 8;

// One entry per drawn knob — op kind, label prefix, and fill Color, two
// encoders per composition (knob 1/2 -> KNOB 1/2, encoder 3/4 -> FULL 1/2,
// encoder 5/6 -> ARC 1/2). Encoders 6 and 7 (0-indexed) have no entry, so
// they're tracked in state.value like any other but never drawn.
const KNOBS = [
  { kind: "knob", label: "KNOB 1", color: paletteColor("sky") },
  { kind: "knob", label: "KNOB 2", color: paletteColor("lime") },
  { kind: "knobfull", label: "FULL 1", color: paletteColor("violet") },
  { kind: "knobfull", label: "FULL 2", color: paletteColor("pink_hot") },
  { kind: "knobarc", label: "ARC 1", color: paletteColor("orange") },
  { kind: "knobarc", label: "ARC 2", color: paletteColor("amber") },
];

function send(obj) {
  process.stdout.write(JSON.stringify(obj) + "\n");
}

function respond(id, result) {
  if (id === undefined || id === null) return;
  send({ id, result });
}

function respondError(id, message) {
  send({ id, error: message });
}

const state = {
  // value[i] is encoder i's accumulated value, clamped to [0,100] at write
  // time so a reversal past the limit responds immediately.
  value: new Array(NUM_ENCODERS).fill(0),
};

function clamp(v, lo, hi) {
  return Math.max(lo, Math.min(hi, v));
}

function handleEncoder(data) {
  const { index, delta } = data;
  if (index >= 0 && index < NUM_ENCODERS) {
    state.value[index] = clamp(state.value[index] + delta, 0, 100);
  }
}

// Op shapes mirror internal/module's Go types exactly — KnobParams is
// {cx,cy,r,k:{...}} (internal/module/frame.go) for all three knob kinds
// ("knob", "knobfull", "knobarc" — same param shape, different renderer),
// and widgets.Knob (the "k" object's type, in ableton-push-hack) has no
// json tags of its own, so its wire keys are its literal Go field names —
// Label/Value/Min/Max/Color, capitalized — same reasoning as color.NRGBA's
// R/G/B/A in the other example modules.
function draw() {
  const black = paletteById(0); // "off" — demonstrates the by-index lookup, paletteColor("off") works identically

  const ops = [
    { kind: "rect", params: { x: 0, y: 0, w: 960, h: 160, c: black } },
    { kind: "header", params: { y: 0, w: 960, h: 20, s: "pushapp - knobs-js (out of process)" } },
  ];

  const r = 30;
  const cy = 80; // vertical center of the content band between the header (0-20) and status bar (140-158)
  const spacing = 960 / KNOBS.length;
  KNOBS.forEach(({ kind, label, color }, i) => {
    const cx = Math.round(spacing * i + spacing / 2);
    ops.push({
      kind,
      params: {
        cx,
        cy,
        r,
        k: { Label: label, Value: state.value[i], Min: 0, Max: 100, Color: color },
      },
    });
  });

  ops.push({
    kind: "statusbar",
    params: { y: 140, w: 960, h: 18, s: "turn encoders 1-6 (7-8 unused)", is_error: false },
  });

  return { ops, failed: 0 };
}

const rl = readline.createInterface({ input: process.stdin, terminal: false });

rl.on("line", (line) => {
  line = line.trim();
  if (!line) return;

  let env;
  try {
    env = JSON.parse(line);
  } catch {
    return;
  }

  const { method, id } = env;
  const params = env.params || {};

  switch (method) {
    case "init":
      respond(id, {});
      break;
    case "handle":
      if (params.kind === "encoder") {
        handleEncoder(params.data || {});
      }
      break;
    case "draw":
      respond(id, draw());
      break;
    case "close":
      respond(id, {});
      rl.close();
      process.exit(0);
      break;
    default:
      if (id !== undefined && id !== null) {
        respondError(id, `unknown method ${JSON.stringify(method)}`);
      }
  }
});
